#!/bin/bash
#

sudo defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor "Automatic Display Enabled" -bool FALSE

#credits to https://github.com/parasew/tahoe-disenshittify/blob/main/restore.sh

defaults write com.apple.widgets.allow-widgets -bool false
defaults write com.apple.Siri SiriHelpEnabled -bool false
defaults write com.apple.appleseed.FeedbackAssistant Autogather -bool false
defaults write com.apple.CrashReporter DialogType -string 'none'
# SECTION: Software Update & Notification Nags
# ---------------------------------------------------------------------------
echo
echo "=== Software Update & Notification Nags ==="
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticCheckEnabled -bool false || true
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate AutomaticDownload -bool false || true
sudo defaults write /Library/Preferences/com.apple.SoftwareUpdate CriticalUpdateInstall -bool false || true
defaults write com.apple.systempreferences AttentionPrefBundleIDs -array

# ---------------------------------------------------------------------------
# SECTION: Finder & Filesystem tweaks
# ---------------------------------------------------------------------------
echo
echo "=== Finder & Filesystem tweaks ==="
chflags nohidden ~/Library"  # reveal user's Library
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
